# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeleKbBot < Formula
  desc "Telegram knowledge base bot powered by the pi SDK"
  homepage "https://github.com/faizhasim/tele-kb-bot"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.2/tele-kb-bot-darwin-amd64.tar.gz"
      sha256 "2b25ee2c6ad83251877ea1e6bf9a3f1452604fdd458d77001e87ac23dea5e966"

      define_method(:install) do
        bin.install "tele-kb-bot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.2/tele-kb-bot-darwin-arm64.tar.gz"
      sha256 "8771460b954248dbe01798cd54e5da53771dd61c7cc917f645573089d379e37b"

      define_method(:install) do
        bin.install "tele-kb-bot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.2/tele-kb-bot-linux-amd64.tar.gz"
      sha256 "a4b41ee24b762a58cdeef99b94f3eb51c248deabdf1431c6f1fa2d792e33b0e7"
      define_method(:install) do
        bin.install "tele-kb-bot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.2/tele-kb-bot-linux-arm64.tar.gz"
      sha256 "0522d39b064b038ddb754a2a7ed69457764e5c1c68d9f8b40667cbd49cf82dff"
      define_method(:install) do
        bin.install "tele-kb-bot"
      end
    end
  end

  def caveats
    <<~EOS
      Optional — qmd enables semantic memory search (vector + hybrid):
        brew install qmd                  # uses Homebrew's Bun
        # or if you manage Bun via mise:
        bun install -g https://github.com/tobi/qmd

      Then set up and enable:
        qmd collection add ~/.config/tele-kb-bot/memory --name tele-kb-bot
        qmd embed
        # config: memory.qmd.enabled: true

      Built-in BM25 works without qmd — no setup needed.
    EOS
  end

  test do
    system "#{bin}/tele-kb-bot version"
  end
end
