# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeleKbBot < Formula
  desc "Telegram knowledge base bot powered by the pi SDK"
  homepage "https://github.com/faizhasim/tele-kb-bot"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.4/tele-kb-bot-darwin-amd64.tar.gz"
      sha256 "025a09d09bab2916ca6a685b7daccda878387c1066c2f640399b322b19d028e4"

      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.4/tele-kb-bot-darwin-arm64.tar.gz"
      sha256 "e13d910152e8b6ab411eb2880d9d2efcf325c83e016f20ca7d9955cc6e99c28c"

      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.4/tele-kb-bot-linux-amd64.tar.gz"
      sha256 "347407b26f37a3fefe92026a8449e511fe754bd2cf6387f905959047fdd9ca12"
      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.4/tele-kb-bot-linux-arm64.tar.gz"
      sha256 "03e7a38c6bd74cf9c28f380257a857d1f2661d3007e4d1eb0815db0a2cd8c7f4"
      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
  end

  def caveats
    <<~EOS
      Before uninstalling, remove the launchd service:
        tele-kb-bot launchd remove

      Optional — qmd enables semantic memory search (vector + hybrid):
        brew install qmd                  # uses Homebrew's Bun
        # or if you manage Bun via mise:
        bun install -g https://github.com/tobi/qmd

      Then set up and enable:
        qmd collection add ~/.config/tele-kb-bot/memory --name tele-kb-bot
        qmd embed
        # config: memory.qmd.enabled: true

      Built-in BM25 works without qmd — no setup needed.
    EOS
  end

  test do
    system "#{bin}/tele-kb-bot version"
  end
end
