# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TeleKbBot < Formula
  desc "Telegram knowledge base bot powered by the pi SDK"
  homepage "https://github.com/faizhasim/tele-kb-bot"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.5/tele-kb-bot-darwin-amd64.tar.gz"
      sha256 "a8fbb93cdddf669053fc5c07d7652d258f1673d87761d8bab2cfa28373fabfde"

      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.5/tele-kb-bot-darwin-arm64.tar.gz"
      sha256 "6cc775422be4106f11b5c337ddab69be3a99009074b078074157ca16a8f3685b"

      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.5/tele-kb-bot-linux-amd64.tar.gz"
      sha256 "cd97be886dba0e796b2b2b7729b8d931ff36c21f2fadaa73f248fe292e0e53f5"
      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/faizhasim/tele-kb-bot/releases/download/v0.1.5/tele-kb-bot-linux-arm64.tar.gz"
      sha256 "f37f8e8371a51aebe5650393ec65903569ee741ea5b2c54fe59e650ab24d21d2"
      define_method(:install) do
        bin.install "tele-kb-bot"
        bin.install "package.json"
      end
    end
  end

  def caveats
    <<~EOS
      Before uninstalling, remove the launchd service:
        tele-kb-bot launchd remove

      Optional — qmd enables semantic memory search (vector + hybrid):
        brew install qmd                  # uses Homebrew's Bun
        # or if you manage Bun via mise:
        bun install -g https://github.com/tobi/qmd

      Then set up and enable:
        qmd collection add ~/.config/tele-kb-bot/memory --name tele-kb-bot
        qmd embed
        # config: memory.qmd.enabled: true

      Built-in BM25 works without qmd — no setup needed.
    EOS
  end

  test do
    system "#{bin}/tele-kb-bot version"
  end
end
